name: 2-Build-Publish-Docker-SCA-Agent

# This step will build and publish the Docker image to https://hub.docker.com/repository/docker/veracodedemolabs/verademo-java-github
# It then runs a SCA Agent scan against the repo and the container and imports into GitHub issues.
# It will run manually or automatically after 1-Checkout-Build-Artifact.yml completes.

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["1-Checkout-Build-Artifact"]
    types:
      - completed

jobs:

  Dockerize-Publish-SCA:

    runs-on: ubuntu-latest

    steps:

# Checkout code
    - uses: actions/checkout@v3

# Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

# Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        push: true
        tags: veracodedemolabs/verademo-java-github:latest

# Running Software Composition Analysis against the local repo and the container
    - name: Veracode SCA Dependency Scanning
      env:
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
      uses: veracode/veracode-sca@v2.0.65
      with:
        github_token: ${{ github.token }}
        update_advisor: true
        create-issues: true
        # A path within the repository where the build definition starts
        path: app
        # Run the SRCCLR with the `--allow-dirty` option
        allow-dirty: true 
    
    - name: SCA Container Scan
      env: 
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
      run: curl -sSL https://download.sourceclear.com/ci.sh | sh -s scan --image veracodedemolabs/verademo-java-github:latest --json=SCA-Container-Results-${{ github.run_id }}.json
      
    - name: Upload artifact with SCA app and container issues for this build
      uses: actions/upload-artifact@v3.1.1
      with:
         name: SCA-Issues-VeraDemoJava-app-container-${{ github.run_id }}
         path: "*.json"       
